DROP TABLE IF EXISTS note;
CREATE TABLE note (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_name TEXT NOT NULL,
    note_content text,
    note_modefied TIMESTAMPTZ DEFAULT now() NOT null
);
DROP TABLE IF EXISTS folders;
CREATE TABLE folders (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folder_name TEXT NOT NULL
);
